### ISSUE TITLE
enablePages requires custom API header to function

### ISSUE THREAD

**Issue by mjcastner** [github/learning-lab-components#156]
## Bug Report

**Current behavior**
Attempting to use the "enablePages" action in Learning Lab will return the following error:
```
HttpError: {"message":"If you would like to help us test the Toggle GitHub Pages with the REST API during its preview period, you must specify a custom media type in the 'Accept' header. Please see the docs for full details.","documentation_url":"https://developer.github.com/v3/repos/pages/#enable-a-pages-site"}
    at /app/node_modules/@octokit/rest/lib/request/request.js:72:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.runActions (/app/lib/context.js:227:24)
    at async Course.runHandler (/app/lib/course.js:187:32)
```

This appears to be because the underlying API method is still in preview state.

**Reproduction**
1. Create an enablePages step without doing any custom API setup.
1. Run the course until you see the step return the above error
1. ???
1. Profit!

**Expected behavior**
enablePages should enable the GitHub Pages feature as expected and gracefully handle the API call.

**Possible solution**
1. Bake in the header to enablePages
1. **Workaround:** Make enablePages a wrapper that deploys the specified branch to gh-pages branch.  If you do this manually in Learning Lab, it has the side effect of automatically enabling GitHub Pages and deploying.  May not work for deployments that need to use the gh-pages branch in a specific context.

**Additional context**
N/A

**Comment by JasonEtco** [comment]
👋 Thanks for opening @mjcastner ❤️ `enablePages` was added in #135, just for the diff. We do include the `Accept` header in the request:

https://github.com/github/learning-lab-components/blob/3caac26912d6ab0363e108b565fd58e7bcded1f1/actions/enablePages/index.js#L6

Buuuut it looks like there was some errant copy-paste:

```diff
- application/vnd.github.switcheroo+json
+ application/vnd.github.switcheroo-preview+json
```

@mjcastner if you're up for a PR that'd be awesome, but if not I can get this fixed 👍
