### ISSUE TITLE
Upgrade to Probot 8/9 and Octokit 16

### ISSUE THREAD

**Issue by JamesMGreene** [github/learning-lab-components#42]
We should be upgrading to a new major version of Probot (`8.x`/`9.x`) and, with it, `@octokit/rest` (`16.x`). These new versions give Learning Lab and, by association, its bot actions a few improvements:

- Shared installation tokens across dynos (via Redis)
- Up-to-date Octokit method names, and new methods
- Improved TypeScript definitions (which comes through in the VSCode autocomplete)
- Enhanced throttling and API request retries (we can remove our custom replication lag workaround)
- Cluster support for throttling via Redis
- A new method for authenticating the client, so that we can have a sweet REPL

This isn't even the full list! :heart_eyes:

That said, there is also an acknowledged performance issue that is currently making us wary of making the move: https://github.com/probot/probot/issues/970 ⚠️ 

So with that in mind, here's what we need to do to get there:

### Update all relevant `type: octokit` action usage in courses

Here's the [full list of deprecated methods](https://github.com/octokit/rest.js/releases/tag/v15.18.0#deprecations) (the list looks huge but course authors haven't actually used most methods). For reference, these changes were made to be more in-line with the GitHub docs; we won't encounter such a significant change in method naming again for a long time.

Some courses are using the `octokit` action with a defined "method". Of those, some of the methods are now deprecated and should be updated.

#### Deprecated methods currently in use in course actions

- [ ] `gitdata.getReference` => `gitdata.getRef`
- [ ] `repos.getHooks()` => `repos.listHooks()`
- [ ] `repos.edit()` => `repos.update()`
- [ ] `issues.addAssigneesToIssue()` => `issues.addAssignees()`
- [ ] `pullRequests.getFiles()` => `pullRequests.listFiles()`

There may be more by the time we can address these.

### Problems

There are a few problems that we will encounter in attempting to tackle this upgrade:

- Existing course registrations for course versions using deprecated methods _will_ **break**
  - Potential compromise: allow a maximum lifetime (e.g. 1-2 months? 🤷‍♂ ) for an active but incomplete course registration
- It would be nice to send Issues or PRs to the course repos for existing courses using these deprecated `octokit` method names but many of them are private
  - Potential solution: the Learning Lab app may be able to open these given its installation on the associated course repos
  - _Buuuut_ failure of the course author to merge the PRs and publish new versions of their course could still result in broken existing and future registrations 😖 

## Long term solution

The better solution long-term will be converting more of these commonly used `octokit` methods into abstracted bot actions of their own so that we can insulate the course authors from such changes in the future.

See #46

**Comment by heiskr** [comment]
Closing per team discussion
