### ISSUE TITLE
Should I be able to use `repos.enablePagesSite`?

### ISSUE THREAD

**Issue by hectorsector** [github/learning-lab-components#43]
I was trying to use [`repos.enablePagesSite`](https://octokit.github.io/rest.js/#octokit-routes-repos-enable-pages-site) and I was unable to. I'm guessing this has to do with the [preview nature of this endpoint](https://developer.github.com/v3/repos/pages/#enable-a-pages-site), but we've been able to use other things in preview in the past, so I'm curious why this one's not working.

**Comment by JamesMGreene** [comment]
There is now an action available for this via PR #135. 🎉
